name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish the app
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Publish
      run: |
        dotnet build
        dotnet publish -c release -r win-x64 -o bin/release/win-x64 -p:PlaywrightPlatform=win --sc
        cp -ri bin/Debug/net6.0/.playwright bin/release/win-x64/
      
    - name: Install Zip
      uses: montudor/action-zip@v1
      
    - name: Create Zip
      run: |
        zip -qq -r Ubi-win-x64.zip win-x64/*
      working-directory: bin/release
      
    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: My Artifact
        path: bin/release/*.zip
        if-no-files-found: warn
        
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: bin/release/*.zip
