name: Publish

env:
  SOURCE_PATH: ${{ GITHUB_ACTION_PATH }}\UbisoftGiveawayNotifier

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish the app
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Publish
      shell: pwsh
      run: |
        dotnet build
        dotnet publish -c release -r win-x64 -o bin\Release\win-x64 --sc
        Copy-Item -Recurse $SOURCE_PATH\bin\Debug\net6.0\.playwright $SOURCE_PATH\bin\Release\win-x64\
      
    - name: Create Zip
      shell: pwsh
      run: |
        Compress-Archive -Path $SOURCE_PATH\bin\Release\win-x64\ -DestinationPath $SOURCE_PATH\bin\win-x64.zip 
      
    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: My Artifact
        path: bin\*.zip
        if-no-files-found: warn
        
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: bin\*.zip
